// WiFi name and password
#define SECRET_SSID "WIFI_NETWORK_NAME"
#define SECRET_PASS "WIFI_NETWORK_PASSWORD"

// AWS IoT
#define SECRET_ENDPOINT "AWS_ENDPOINT_URL"
#define SECRET_AWS_KEY "AWS_KEY"
#define SECRET_AWS_SECRET_KEY "AWS_SECRET_KEY"
